### PID control for quadcopter

controller/feedforward_flag: false

controller/pitch/ctrl_loop_rate: 40
controller/roll/ctrl_loop_rate: 40
controller/throttle/ctrl_loop_rate: 40
controller/yaw/ctrl_loop_rate: 40

# throttle 
controller/throttle/pos_p_gain: 250.0  #0.25 * 1000
controller/throttle/pos_i_gain: 250.0 #250.0  #0.25 * 1000
controller/throttle/pos_d_gain: 280.0  #0.28 * 1000
controller/throttle/const_i_ctrl_thre_land: 0.0
controller/throttle/offset: 1000
controller/throttle/pos_limit: 1800
controller/throttle/pos_p_limit: 150
controller/throttle/pos_i_limit: 800
controller/throttle/pos_d_limit: 180

# yaw 
controller/yaw/pos_p_gain: 100.0 #0.1 * 1000
controller/yaw/pos_i_gain: 0.0 #0.0001 * 1000
controller/yaw/pos_d_gain: 0.0
controller/yaw/pos_limit: 100
controller/yaw/pos_p_limit: 100
controller/yaw/pos_i_limit: 50
controller/yaw/pos_d_limit: 50
controller/yaw/vel_value_limit: 0
#controller/yaw/i_enable_limit: 0.25

# pitch 
controller/pitch/pos_p_gain: 0.1
controller/pitch/pos_i_gain: 0.01 # old : 0.05
controller/pitch/pos_i_gain_hover: 0.005
controller/pitch/pos_d_gain: 0.55 #for mocap: 0.5,  for opt 0.4
controller/pitch/vel_p_gain: 0.55 #for mocap: 0.48, for opt 0.4
controller/pitch/vel_i_gain: 0.005 
controller/pitch/offset: 0
controller/pitch/pos_limit: 200 # rook1: 200
controller/pitch/pos_p_limit: 100 #rook1 :100
controller/pitch/pos_i_limit: 100 #rook1 :100 
controller/pitch/pos_d_limit: 100 #rook1 :100
controller/pitch/vel_value_limit: 0.8
controller/pitch/i_enable_limit: 0.4

#  roll 
controller/roll/pos_p_gain: 0.1
controller/roll/pos_i_gain: 0.01 #old : 0.05
controller/roll/pos_i_gain_hover: 0.005
controller/roll/pos_d_gain: 0.55 # for mocap 0.5, for opt 0.4
controller/roll/vel_p_gain: 0.55 # for mocap 0.5, for opt 0.4
controller/roll/vel_i_gain: 0.005
controller/roll/pos_limit: 200 #rook1 : 200
controller/roll/pos_p_limit: 100 #rook1 :100
controller/roll/pos_i_limit: 100 #rook1 : 100
controller/roll/pos_d_limit: 100 #rook1 : 100
controller/roll/vel_value_limit: 0.8
controller/roll/i_enable_limit: 0.4

#others
controller/land_gain_slow_rate: 0.3