motor_info:
        min_pwm: 0.60 # = 1200 [ms]
        max_pwm: 0.86 # = 1720 [ms]
        force_landing_thrust: 7 #[N]
        m_f_rate: 0 # should be zero, because of the dual rotor
        pwm_conversion_mode: 1 # Polynominal Mode
        vel_ref_num: 4
        ref1:        
                voltage: 25.2
                max_thrust: 18.04 # N 
                polynominal4: -5.7063259 # x 10^4
                polynominal3: 15.577885 # x10^3
                polynominal2: -8.8434316 # x10^2
                polynominal1: 13.882688 # x10
                polynominal0: 58.697129 # x1
        ref2:
                voltage: 24.2
                max_thrust: 16.27 # N
                polynominal4: -8.9762987 # x 10^4
                polynominal3: 25.174311 # x10^3
                polynominal2: -18.136790 # x10^2
                polynominal1: 18.573183 # x10
                polynominal0: 58.265334 # x1
        ref3:        
                voltage: 23.2
                max_thrust: 15.25 # N
                polynominal4: -9.9940524 # x 10^4
                polynominal3: 25.287343 # x10^3
                polynominal2: -14.915788 # x10^2
                polynominal1: 17.404827 # x10
                polynominal0: 58.512989 # x1
        ref4:        
                voltage: 22.2
                max_thrust: 14.22 # N
                polynominal4: -14.725489 # x 10^4
                polynominal3: 35.482073 # x10^3
                polynominal2: -21.115724 # x10^2
                polynominal1: 19.991898 # x10
                polynominal0: 58.454254 # x1
