motor_info:
        min_pwm: 0.5 # 1000 ~ dshot 0
        max_pwm: 0.9 # 1800 ~ dshot 1600
        min_thrust: 0.0 # [N]
        force_landing_thrust: 6.0 # [N]
        krpm_rate: 8.31255 # 1/0.1203 (kRPM)^2/N
        m_f_rate: -0.0153
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 5
        ref1:
                voltage: 24.17 # [V]
                max_thrust: 18.3590 # [N]
                polynominal2: 0.07188 # x10
                polynominal1: -5.13410  # x10
                polynominal0: 7.17114 # x1
        ref2:
                voltage: 23.24 # [V]
                max_thrust: 17.8578 # [N]
                polynominal2: 0.07595 # x10
                polynominal1: -5.99231  # x10
                polynominal0: 10.67755 # x1
        ref3:
                voltage: 22.31 # [V]
                max_thrust: 16.6075 # [N]
                polynominal2: 0.07275 # x10
                polynominal1: -5.83702  # x10
                polynominal0: 10.67715 # x1
        ref4:
                voltage: 21.38 # [V]
                max_thrust: 15.5294 # [N]
                polynominal2: 0.06666 # x10
                polynominal1: -5.28465 # x10
                polynominal0: 9.43016 # x1
        ref5:
                voltage: 20.44 # [V]
                max_thrust: 14.6201 # [N]
                polynominal2: 0.06519 # x10
                polynominal1: -5.34097  # x10
                polynominal0: 10.11535 # x1
