wrench_estimator_name: aerial_robot_control::WrenchEstMomAcc

controller:
  if_use_est_wrench_4_control: true

  acceleration_observer:
    force_alpha_weight: 0.5  # alpha for low-pass filter  (0.0 ~ 1.0)

  momentum_observer:
    momentum_observer_torque_weight: 1.5