aerial_robot_control_name: aerial_robot_control/crobat_controller

controller:
  torque_allocation_matrix_inv_pub_interval: 0.05
  wrench_allocation_matrix_pub_interval: 0.1
  gimbal_calc_in_fc : false
  gravity_comp_flag_: true

  xy:
    p_gain: 30.0 #5.0
    i_gain: 2.0 #0.05
    d_gain: 12.0 #5.0
    limit_sum: 1000 #10
    limit_p: 1000 #20
    limit_i: 1000 #40
    limit_d: 1000 #20

  z:
    p_gain: 20.0 #5.0
    i_gain: 3.0 #2.5
    d_gain: 5.0 #5.0
    limit_err_p: 1000 #1.0
    limit_sum: 1000 #10
    limit_p: 1000 #20
    limit_i: 1000 #40
    limit_d: 1000 #20
    landing_err_z: -0.2 #-0.2
    force_landing_descending_rate: -0.03 #-0.6

  yaw:
    p_gain: 15.0 #6.0
    i_gain: 2.0 #1.0
    d_gain: 7.0 #4.0
    limit_err_p: 1000 #0.4
    limit_sum: 1000 #10
    limit_p: 1000 #20
    limit_i: 1000 #40
    limit_d: 1000 #20
    need_d_control: true

  roll_pitch:
    p_gain: 50.0 #18.0
    i_gain: 2.0 #1.0
    d_gain: 25.0 #8.0
    limit_sum: 1000 #10
    limit_p: 1000 #20
    limit_i: 1000 #40
    limit_d: 1000 #20

