servo_controller:
  pos_pub_topic: extra_servo_cmd
  gimbals:
    angle_sgn: -1
    angle_scale: 0.017453
    zero_point_offset: 90

    controller1:
      id: 4
      name: gimbal1
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller2:
      id: 5
      name: gimbal2
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController

    controller3:
      id: 6
      name: gimbal3
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController
    controller4:
      id: 7
      name: gimbal4
      simulation:
        pid: {p: 5.0, i: 0.1, d: 0.1, i_clamp_max: 2.0, i_clamp_min: -2.0}
        init_value: 0
        type: effort_controllers/JointPositionController
