j1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 1
        init: 0
        min: 0
        max: 4095


j2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 2
        init: 0
        min: 0
        max: 4095


j3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 3
        init: 0
        min: 0
        max: 4095


j4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint4
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 4
        init: 0
        min: 0
        max: 4095


j5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint5
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 5
        init: 0
        min: 0
        max: 4095


j6_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint6
    joint_speed: 7.5 #0.2 /0.6
    motor:
        id: 6
        init: 0
        min: 0
        max: 4095


j7_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint7
    joint_speed: 7.5 #0.1 /0.6
    motor:
        id: 7
        init: 0
        min: 0
        max: 4095


j8_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint8
    joint_speed: 7.5 #0.1 /0.6
    motor:
        id: 8
        init: 0
        min: 0
        max: 4095
