mpc_solver_name: aerial_robot_control::mpc_solver::TiltQdServoThrustDistImpMdlMPCSolver
aerial_robot_control_name: aerial_robot_control/nmpc_controller/tilt_mt/servo_thrust_imp_nmpc

controller:
  nmpc:
    T_samp: 0.01  # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # seconds
    T_step: 0.1  # seconds

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 30 # N
    thrust_min: 0 # N

    a_max: 3.1416  # 30 degree ~ 0.5    1.5708 rad ~ 90 deg
    a_min: -3.1416

    # params for the cost function
    epsilon: 0.00001  # avoid the dividend is 0 when M = 0
    # position
    pMxy: 1.5
    pMz: 1.5
    Qv_xy: 10  # pDxy
    Qv_z: 10  # pDz
    Qp_xy: 6  # pKxy
    Qp_z: 6  # pKz

    # orientation
    oMxy: 0.9
    oMz: 0.9
    Qw_xy: 10  # oDxy
    Qw_z: 10  # oDz
    Qq_xy: 6  # oKxy
    Qq_z: 6  # oKz

    # actuators
    Qa: 2
    Qt: 2  # t is for thrust

    Rtc_d: 1  # difference of ftc
    Rac_d: 250  # difference of ac

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_phys_params: false
    is_debug: false
