servo_controller:

  joints:
    angle_sgn: 1
    angle_scale: 0.00076699
    zero_point_offset: 2047
    torque_scale: 0.03483 # convert to N*m

    # for simulation
    simulation:
      pid: {p: 50.0, i: 0.01, d: 2.0}
      init_value: 1.57
      type: effort_controllers/JointPositionController

    # should be in order in terms of kinematics model
    # i.e. joint1 -> jointN
    controller1:
      id: 0
      name: joint1
      angle_sgn: -1
      #angle_max: 1.58 # you can specify for each controller

      #simulaton:  # you can specify for each controller
        #type: effort_controllers/JointPositionController
        #pid: {p: 50.0, i: 0.01, d: 2.0}
        #init_value: 0

    controller2:
      id: 1
      name: joint2
      angle_sgn: -1
    controller3:
      id: 2
      name: joint3
    
    controller4:
      id: 4
      name: soft_joint2
      angle_sgn: 0
      simulation:
        init_value: 0.0

    controller5:
      id: 5
      name: soft_joint3
      angle_sgn: 0
      simulation:
        init_value: 0.0

    controller6:
      id: 6
      name: soft_joint4
      angle_sgn: 0
      simulation:
        init_value: 0.0
    
  gimbals:
    angle_sgn: 1
    angle_scale: 0.001534
    zero_point_offset: 2047

    simulation:
      pid: {p: 50.0, i: 0.01, d: 0.0}
      init_value: 0.0
      type: effort_controllers/JointPositionController

    controller1:
      id: 3
      name: gimbal_joint1
      simulation:
        init_value: 0.0
