### Differential Flatness PID control for hydrusx quad type

# alt [N]
controller/alt/offset: 0
controller/alt/limit: 16.5
controller/alt/p_term_limit: 16.5
controller/alt/i_term_limit: 16.5
controller/alt/d_term_limit: 16.5
controller/alt/alt_landing_const_i_ctrl_thresh: -0.2

# xy [rad]
controller/xy/p_gain: 0.2 
controller/xy/i_gain: 0.002
controller/xy/hovering_i_gain: 0.001
controller/xy/d_gain: 0.4
controller/xy/limit: 0.3 
controller/xy/p_term_limit: 0.2 
controller/xy/i_term_limit: 0.15
controller/xy/d_term_limit: 0.2
controller/xy/x_offset: 0
controller/xy/y_offset: 0
controller/xy/xy_vel_weak_gain_sub_name: /velocity_control_gain_change

# yaw [N]
controller/yaw/limit: 10.0
controller/yaw/p_term_limit: 10.0
controller/yaw/i_term_limit: 10.0
controller/yaw/d_term_limit: 10.0

