sensor_plugin:
        imu:
                imu_board: 1 #d_board
                imu_topic_name: /imu
                level_acc_noise_sigma: 0.02
                z_acc_noise_sigma: 0.05 #real:0.05
                acc_bias_noise_sigma: 0.001 #0.005#0.04
                angle_bias_noise_sigma: 0.0001 #good for EKF
                calib_time: 2.0
