aerial_robot_control_name: aerial_robot_control/delta_controller

controller:
  control_verbose: false
  hovering_approximate: false
  aerial_mode_add_joint_torque_constraint: false
  use_fc_for_att_control: false

  xy:
    p_gain: 5.0
    i_gain: 1.0
    d_gain: 3.0
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 5.0
    i_gain: 1.5
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0
    force_landing_descending_rate: -0.5

  roll_pitch:
    start_rp_integration_height: 0.01

  roll:
    p_gain: 20.0
    i_gain: 0.5
    d_gain: 5.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  pitch:
    p_gain: 20.0
    i_gain: 0.5
    d_gain: 5.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  yaw:
    p_gain: 4.0
    i_gain: 2.0
    d_gain: 6.0
    limit_err_p: 2.0
    limit_sum: 20.0
    limit_p: 3.0
    limit_i: 20.0
    limit_d: 20.0

    need_d_control: true
