zeros:
  gimbal1: 0
  gimbal2: 0
  gimbal3: 0
  gimbal4: 0
  gimbal_joint5: 0
  joint1: 1.57
  joint2: 1.57
  joint3: 1.57
  soft_joint2: 0.0
  soft_joint3: 0.0
  servo_joint1: 0.0
  servo_joint2: 0.0
  soft_joint5: 0.0
  soft_joint6: 0.0
  dummy_joint1: 0.0
  dummy_joint2: 0.0
