hydrusx:
    # for control bridge
    joint_num: 5
    joint1:
        init_angle: 1.0472
    joint2:
        init_angle: 1.0472
    joint3:
        init_angle: 1.0472
    joint4:
        init_angle: 1.0472
    joint5:
        init_angle: 1.0472

    # test for non-attitude control mode
    baselink_name: fc

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint1
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint2
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint3
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint4
        pid: {p: 50.0, i: 0.01, d: 2.0}
    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint5
        pid: {p: 50.0, i: 0.01, d: 2.0}
    attitude_controller:
        type: flight_controllers/SimulationAttitudeController
        