# FAST LIO
common:
        imu_topic: /dragon/sensor_plugin/imu1/ros_converted
mapping:
        extrinsic_T: [ -0.193, 0.0, 0.0495 ]
# z: 0.0025 (IMU to Livox bottom) + 0.047 (Livox bottom to O orign)

# KF
sensor_plugin:
  vo:
    sensor_frame: fc
