sensor_plugin:
  vo:
    vo_sub_topic_name: /zed/odom
    vo_noise_sigma: 0.001
    joint: zed_mini_servo_joint
    sensor_frame: zed_camera_center
    reference_frame: fc
    vio_flag: true
    valid_yaw: true
    debug_verbose: false
    time_sync: true
    delay: -0.15
    servo_init_angle: -1.570796
    servo_index: 1
    #servo_min_pwm: 550
    #servo_max_pwm: 2450
    variable_sensor_tf_flag: true
    vo_servo_topic_name: /hydrusx/extra_servos_ctrl
    servo_auto_change_flag: true
    servo_height_thresh: 0.8
    servo_vel: 0.08
    servo_control_rate: 0.025

# for gazebo simulation of servo motor
hydrusx:
  servo_controller:
    extra_servos:
      ctrl_pub_topic: /extra_servo_cmd

      angle_sgn: 1
      angle_scale: 0.00165347
      zero_point_offset: 1500 # min_pwm: 550; max_pwm: 2450

      # for simulation
      simulation:
        pid: {p: 10.0, i: 0.01, d: 0.0}
        init_value: 0 # -1.570796
        type: effort_controllers/JointPositionController

      controller1:
        id: 1
        name: zed_mini_servo_joint
