#Hydra3 config

link_joint_offset: 0.205

link_base_center_mass: 0.238

link_joint_mass: 0.0785
controller1_mass: 0.022
controller2_mass: 0.104 #old: 0.093Kg(93g)
controller2_offset: 0.189 #old: 0.178

root_link: 2

link1_base_rod_mass: 0.105 

propeller1_direction: -1 #default: -1
propeller1_order: 0

link2_base_rod_mass: 0.1 

propeller2_direction: 1 #default: 1
propeller2_order: 1

link3_base_rod_mass: 0.094  

propeller3_direction: -1 #default :1
propeller3_order: 3

link4_base_rod_mass: 0.094  

propeller4_direction: 1
propeller4_order: 2

debug_log: false
debug2_log: false


lqi_thread_rate: 10.0
q_roll: 10.0  #  100
q_roll_d: 10.0  #  100
q_roll_i: 10.0 #  10
q_pitch: 10.0  #  100
q_pitch_d: 10.0  #  100
q_pitch_i: 10.0 #  10

q_yaw: 10.0 # 10 
q_yaw_d: 10.0 #  10
q_yaw_i: 1 # 1

q_z: 10.0
q_z_d: 10.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

dist_thre: 0.05 # 0.04 is enough to calculate the planning, resulting in 0.07 ~ 0.08
f_max: 8.2
f_min: 2.0
