j1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 0.1 #0.4 /0.6
    motor:
        id: 1
        init: 0
        min: 0
        max: 1023

j2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 0.1 #0.4 / 0.6
    motor:
        id: 2
        init: 0
        min: 0
        max: 1023

j3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint3
    joint_speed: 0.1 #0.4 /0.6
    motor:
        id: 3
        init: 0
        min: 0
        max: 1023
