aerial_robot_control_name: aerial_robot_control/under_actuated_controller

controller:
  xy:
    p_gain: 0.25 #5.0
    i_gain: 0.0025 #0.05
    d_gain: 0.25 #5.0
    limit_sum: 0.15 #3
    limit_p: 0.15 #3
    limit_i: 0.075 #1.5
    limit_d: 0.015 #3

  z:
    p_gain: 0.25 #5.0
    i_gain: 0.125 #2.5
    d_gain: 0.25 #5.0
    limit_err_p: 0.05 #1.0
    limit_sum: 0.5 #10
    limit_p: 1 #20
    limit_i: 2 #40
    limit_d: 1 #20
    landing_err_z: -0.01 #-0.2
    force_landing_descending_rate: -0.03 #-0.6

  yaw:
    p_gain: 0.3 #6.0
    i_gain: 0.05 #1.0
    d_gain: 0.2 #4.0
    limit_err_p: 0.02 #0.4
    limit_sum: 1.0 #20.0
    limit_p: 1.0 #20.0
    limit_i: 1.0 #20.0
    limit_d: 1.0 #20.0
    need_d_control: false

  roll_pitch:
    p_gain: 0.9 #18.0
    i_gain: 0.05 #1.0
    d_gain: 0.4 #8.0
    limit_sum: 1.0 #20.0
    limit_p: 1.0 #20.0
    limit_i: 1.0 #20.0
    limit_d: 1.0 #20.0

