motor_info:
        min_pwm: 0.55 # 1180 [ms]
        max_pwm: 0.95 # 1875 [ms]
        min_thrust: 0.1 #  [N]
        force_landing_thrust: 0.1 #[N]
        m_f_rate: 0
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 1
        ref1:
                voltage: 8.4
                max_thrust: 0.8 # N 
                polynominal2: -0.0029378523655137156 # x10
                polynominal1: 0.6466870337531405 # x10
                polynominal0: -2.700687530358138 # x1
        ref2:
                voltage: 7.8
                max_thrust: 0.7 # N 
                polynominal2: -0.002872083872834844 # x10
                polynominal1: 0.6067475831427108 # x10
                polynominal0: -2.502039479756373 # x1
        ref3:
                voltage: 7.2
                max_thrust: 0.7 # N 
                polynominal2: -0.0011283193016175086 # x10
                polynominal1: 0.3542768335931359 # x10
                polynominal0: -1.6495288524866654 # x1