sensor_plugin:
        imu:
                imu_topic_name: imu
                level_acc_noise_sigma: 0.05
                z_acc_noise_sigma: 0.05
                level_acc_bias_noise_sigma: 0.001 # (> 0 means to do the acc bias estimation by kalman filter)
                z_acc_bias_noise_sigma: 0.001 # (= 0 means not to do the acc bias estimation by kalman filter)
                angle_bias_noise_sigma: 0.0002 #good for EKF
                calib_time: 2.0
