sensor_plugin:
  gps: #single GPS
    min_est_sat_num: 7
    vel_noise_sigma: 0.02 #0.05 -> 0.01 -> 0.02
    pos_noise_sigma: 1.0
    gps_ros_sub_name: sim/gps/fix
    sensor_frame: gps
    ned_flag: true #north(x)-east(y)-down(z) frame
    time_sync: true
    delay: -0.45 # daylight: -0.45, night: -0.5
    #only_use_vel: true # debug
