#Dragon Quad config

joint_state_sub_name: /dragon/joint_states

verbose: false
control_rate: 15.0

baselink: fc

only_three_axis_mode: true

q_roll: 400
q_roll_d: 40
q_roll_i: 10.0
q_pitch: 400
q_pitch_d: 40
q_pitch_i: 10.0

q_yaw: 50
strong_q_yaw: 200
q_yaw_d:  50
q_yaw_i: 0.1

q_z: 20.0
q_z_d: 30.0
q_z_i: 10.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0

dist_thre: 0.03 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 15.0
f_min: 2.0
