servo_controller:
  state_sub_topic: servo/states
  ctrl_pub_topic: servo/target_states

  joints:
    angle_sgn: 1    
    angle_scale: 0.00076699     
    zero_point_offset: 2047     
    torque_scale: 1.0 # TODO please update the scale
    
    # for simulation
    simulation:
      pid: {p: 2.75, i: 0.0, d: 0.0}
      # pid: {p: 10.0, i: 0.0, d: 5.0}
      init_value: 1.0
      # type: effort_controllers/JointEffortController
      type: effort_controllers/JointPositionController

    controller1:
      name: joint_1_1
      simulation:
        init_value: -1.0
    controller2:
      name: joint_1_2
      simulation:
        init_value: -1.0
    controller3:
      name: joint_1_3
      simulation:
        init_value: -1.0
    controller4:
      name: joint_2_1
      simulation:
        init_value: -1.0
    controller5:
      name: joint_2_2
      simulation:
        init_value: -1.0
    controller6:         
      name: joint_2_3
      simulation:
        init_value: -1.0
    controller7:
      name: joint_3_1
      simulation:
        init_value: -1.0
    controller8:
      name: joint_3_2
      simulation:
        init_value: -1.0
    controller9:
      name: joint_3_3
      simulation:
        init_value: -1.0
    controller10:
      name: joint_4_1
      simulation:
        init_value: -1.0
    controller11:
      name: joint_4_2
      simulation:
        init_value: -1.0
    controller12:
      name: joint_4_3
      simulation:
        init_value: -1.0

