waypoints:
  # - [2.0, 3.0]
  # - [3.0, -2.0]
  # - [5.0, 0.0]

  # - [3.0, 0.0]
  # - [3.0, 3.0]
  # - [5.0, 5.0]
  # - [5.0, 3.0]

  - [0.0, 0.7]
  - [-1.5, -0.7]
  - [-2.0, 0.0]


  # - [2.0, -1.0]
  # - [4.0, -4.0]
  # - [5.0, -2.0]
  # - [5.0, 1.0]

  # - [1.0, 2.0]
  # - [4.0, 2.0]
  # - [4.0, -2.0]
  # - [2.0, -2.0]

  # - [4.0, 3.0]
  # - [4.0, 1.0]
  # - [5.0, -1.0]
  # - [4.0, -3.0]

  # - [2.0, -2.0]
  # - [5.0, 2.0]
  # - [5.0, 4.0]
  # - [3.0, 4.0]

#7.8~8.0
# - [3.0, 0.0]
  # - [4.0, 1.0]
  # - [3.0, 2.0]
  # - [5.0, 2.0]

  # - [2.0, -2.0]
  # - [2.0, -3.0]
  # - [4.0, -3.0]
  # - [4.0, -1.0]
 
  # - [1.0, 1.0]
  # - [2.0, -1.0]
  # - [3.0, 1.0]
  # - [4.0, 0.0]

  # - [3.0, -2.0]	
  # - [3.0, 0.0]
  # - [2.0, 0.0]
  # - [1.0, 1.0]

  # - [2.0, 0.0]
  # - [4.0, 2.0]
  # - [2.0, 4.0]
  # - [1.0, 3.0]

  # - [2.0, 2.0]
  # - [2.0, -1.0]
  # - [4.0, -1.0]
  # - [4.0, -2.0]
