sensor_plugin:
        mocap:
                pos_noise_sigma: 0.0002
                angle_sigma: 0.005
                acc_bias_noise_sigma: 0.001 # force acc bias estimation by kalman filter
                unhealth_level: 3
                health_timeout: 0.5
                time_sync: false
                mocap_sub_name: mocap/pose
