# Sensor Fuser Loader
estimator:
        # sensor plugin
        sensor_list:
        - sensor_plugin/mocap

# EGOMOTION_ESTIMATION_MODE = 0
# GROUND_TRUTH_MODE = 1
# EXPERIMENT_MODE = 2

/sensor_plugin:
        mocap:
                estimate_mode: 2 #1 << 1
                unhealth_level: 3
                health_timeout: 0.5
                ground_truth_sub_name: /hydrusx/ground_truth
