#HydraX config

link_joint_offset: 0.205

link_base_center_mass: 0.238

link_joint_mass: 0.0785
controller1_mass: 0.0
controller2_mass: 0.093

link_num: 6
root_link: 3

link1_base_rod_mass: 0.105 
propeller1_direction: -1
propeller1_order: 0

link2_base_rod_mass: 0.094
propeller2_direction: 1
propeller2_order: 1

link3_base_rod_mass: 0.094  
propeller3_direction: -1
propeller3_order: 2

link4_base_rod_mass: 0.094  
propeller4_direction: 1
propeller4_order: 3

link5_base_rod_mass: 0.094  
propeller5_direction: -1
propeller5_order: 4

link6_base_rod_mass: 0.094  
propeller6_direction: 1
propeller6_order: 5

lqi_thread_rate: 10.0
q_roll: 100.0  #  100
q_roll_d: 100.0  #  100
q_roll_i: 10.0 #  10
q_pitch: 100.0  #  100
q_pitch_d: 100.0  #  100
q_pitch_i: 10.0 #  10

q_yaw: 10.0 # 10 
q_yaw_d: 10.0 #  10
q_yaw_i: 1 # 1

q_z: 1.0
q_z_d: 1.0
q_z_i: 1.0

r1: 1.0
r2: 1.0
r3: 1.0
r4: 1.0
r5: 1.0
r6: 1.0

dist_thre: 0.17 # 0.17 is max now for planning, 0.06 is enough for l, s pose
f_max: 8.2
f_min: 2.0
