aerial_robot_control_name: aerial_robot_control/hydrus_tilted_lqi_controller

controller:
  xy:
    p_gain: 2.3
    i_gain: 0.02
    d_gain: 4.0
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 3.6
    i_gain: 1.55
    d_gain: 3.4
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0 # m / s^2
    limit_i: 25.0 # m / s^2
    limit_d: 25.0 # m / s^2
    landing_err_z: -0.55

  # yaw [N]
  yaw:
    limit_err_p: 0.4
    limit_sum: 15.0
    limit_p: 15.0
    limit_i: 15.0
    limit_d: 15.0

  # LQI gain generator
  lqi:
    gain_generate_rate: 15.0
    gyro_moment_compensation: true
    clamp_gain: true

    roll_pitch_p: 2000
    roll_pitch_i: 20
    roll_pitch_d: 150

    yaw_p: 100
    yaw_i: 0.5
    yaw_d: 50

    r1: 1.0
    r2: 1.0
    r3: 1.0
    r4: 1.0

    trans_constraint_weight: 100
    att_control_weight: 1
