# Teleop Basic Param

flight_navigation_plugin_name: aerial_robot_navigation/hydrus_xi_under_actuated_navigation

navigation:
  xy_control_mode: 0
  # World Pos Control Mode: 0
  # World Vel Control Mode: 2
  # Local Vel Control Mode: 3
  # Attitude Control Mode: 4

  takeoff_height: 0.6
  outdoor_takeoff_height: 1.5

  # teleop operation
  max_target_vel: 0.5
  joy_target_vel_interval: 0.005  # 0.2 / 20 = 0.01, 0.005 ~ 0.01  m/s
  joy_target_alt_interval: 0.02
  max_target_yaw_rate: 0.1 #  0.05
  teleop_local_frame: fc

  cmd_vel_lev2_gain : 2.0
  nav_vel_limit : 0.3

  gain_tunning_mode: 0
  max_target_tilt_angle: 0.2
  cmd_angle_lev2_gain : 1.5

  # gps waypoint
  gps_waypoint_threshold: 3.0
  gps_waypoint_check_du: 1.0

  # gimbal vectoring planner
  plan_verbose: false
  maximize_yaw: false # true: maximize min yaw torque, false: maximize feasible control torque convex
  plan_freq: 20.0
  baselink_rot_thresh: 0.01
