aerial_robot_control_name: aerial_robot_control/delta_controller

controller:
  control_verbose: false
  torque_allocation_matrix_inv_pub_interval: 0.02
  wrench_allocation_matrix_pub_interval: 0.1
  hovering_approximate: false
  wrench_estimate_flag: true

  rolling_minimum_lateral_force: 0.2
  ground_mu: 3.0
  opt_add_joint_torque_constraint: true
  nlopt:
    thrust_weight: 1.0
    gimbal_linear_solution_dist_weight: 1.0
    gimbal_current_angle_dist_weight: 3.0
    gimbal_center_dist_weight: 2.0
    joint_torque_weight: 6.0

  xy:
    p_gain: 5.0
    i_gain: 1.0
    d_gain: 3.0
    limit_sum: 4.0
    limit_p: 12.0
    limit_i: 12.0
    limit_d: 12.0

  z:
    p_gain: 5.0
    i_gain: 1.5
    d_gain: 2.5
    limit_err_p: 1.0
    limit_sum: 25.0 # N for clamping thrust force
    limit_p: 25.0
    limit_i: 25.0
    limit_d: 25.0
    force_landing_descending_rate: -0.5

  roll_pitch:
    start_rp_integration_height: 0.01

  roll:
    p_gain: 15.0
    i_gain: 1.0
    d_gain: 2.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  pitch:
    p_gain: 15.0
    i_gain: 1.0
    d_gain: 2.0
    limit_sum: 50.0
    limit_p: 50.0
    limit_i: 50.0
    limit_d: 50.0

  yaw:
    p_gain: 4.0
    i_gain: 2.0
    d_gain: 6.0
    limit_err_p: 2.0
    limit_sum: 20.0
    limit_p: 3.0
    limit_i: 20.0
    limit_d: 20.0

    need_d_control: true

standing_controller:
  gravity_compensate_weights: [1.0, 1.0, 1.0]
  xy:
    p_gain: 1.5
    i_gain: 0.0
    d_gain: 2.5

  z:
    p_gain: 20.0
    i_gain: 1.5
    d_gain: 2.5

  roll:
    p_gain: 5.0
    i_gain: 0.1
    d_gain: 8.0

  pitch:
    p_gain: 6.0
    i_gain: 0.0
    d_gain: 4.0

  yaw:
    p_gain: 2.0
    i_gain: 0.0
    d_gain: 1.0

rolling_controller:
  gravity_compensate_weights: [0.0, 1.0, 0.0]
  xy:
    p_gain: 1.5
    i_gain: 0.0
    d_gain: 2.5

  z:
    p_gain: 20.0
    i_gain: 1.5
    d_gain: 2.5

  roll:
    p_gain: 13.0
    i_gain: 0.1
    d_gain: 5.0

  pitch:
    p_gain: 6.0
    i_gain: 0.1
    d_gain: 3.0

  yaw:
    p_gain: 2.0
    i_gain: 0.1
    d_gain: 1.0

